# Copyright (c) 2026 The codem37 Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

template("mojom") {
  group(target_name) {
    forward_variables_from(invoker, [ "public_deps", "deps" ])
    if (defined(invoker.sources)) {
      not_needed(invoker, [ "sources" ])
    }
  }
}
