# Copyright (c) 2026 The codem37 Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//ui/webui/resources/tools/build_webui.gni")

build_webui("build") {
  grd_prefix = "mine_downloads"
  static_files = [ "downloads.html" ]
  ts_files = [
    "downloads.ts",
    "app.ts",
    "mojo_client.ts",
    "components/download_list.ts",
    "components/download_item.ts",
    "components/download_start_dialog.ts",
  ]
  mojo_files = [
    "$root_gen_dir/src/mine/fetcher/mojom/fetcher.mojom-webui.ts",
  ]
  mojo_files_deps = [ "//src/mine/fetcher/mojom:mojom_ts__generator" ]
}
